liip_imagine:
    driver: "gd" # or imagick if available
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.project_dir%/public/media/uploads"
    filter_sets:
        cache: ~
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [256, 256], mode: inset }
        medium:
            quality: 90
            filters:
                thumbnail: { size: [896, 896], mode: inset }
        large:
            quality: 100
            filters:
                thumbnail: { size: [1600, 1600], mode: inset }
