controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
catch_all:
    path: /{path}
    controller: App\Controller\ClientController::index
    requirements:
        path: ".*"
    defaults:
        path: ""
