# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  images_directory: "%kernel.project_dir%/public/media/uploads"

services:
  Symfony\Component\HttpKernel\Controller\ArgumentResolverInterface: "@argument_resolver"

  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"

  Themes\:
    resource: "../Themes/*/Actions/*"
    autowire: true
    public: true

  App\Twig\AppExtension:
    arguments:
      $entityManager: "@doctrine.orm.default_entity_manager"
    tags: ["twig.extension"]

  App\Service\ImageUploader:
    arguments:
      $targetDirectory: "%images_directory%"
      $loader: "@liip_imagine.binary.loader.default"

  App\Controller\ClientController:
    arguments:
      $argumentResolver: "@argument_resolver"
      $fullContainer: "@service_container"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
